version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    extra_hosts:
      - "mysql:172.18.0.1"
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=qweqwe
      - MYSQL_DATABASE=api
      - MYSQL_USER=user
      - MYSQL_PASSWORD=qweqwe
    ports:
      - "3307:3306"
    command:
      - "--sort_buffer_size=500000000"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"